# Generated by Django 2.2.7 on 2019-11-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('fw_version', models.CharField(max_length=32)),
                ('serial', models.CharField(max_length=64, unique=True)),
                ('vendor', models.CharField(max_length=64)),
            ],
        ),
    ]
