# Generated by Django 2.2.7 on 2019-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
