# Generated by Django 2.2.7 on 2019-12-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvs', '0002_remove_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='books',
        ),
        migrations.AddField(
            model_name='library',
            name='books',
            field=models.ManyToManyField(related_name='books', to='cbvs.Book'),
        ),
    ]
